name: Release

on:
  push:
    tags:
      - 'v*'  # triggers on tags like v1.0.0, v2.3.1

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        EXT=""
        if [ "${GOOS}" == "windows" ]; then EXT=".exe"; fi
        OUTPUT_NAME=tiffcompressor-${{ matrix.goos }}-${{ matrix.goarch }}$EXT
        go build -o $OUTPUT_NAME

    - name: Upload binaries
      uses: softprops/action-gh-release@v1
      with:
        files: |
          tiffcompressor-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

